In [1]:
from numpy.random import seed
seed(888)
from tensorflow import set_random_seed
set_random_seed(404)
from tensorflow .compat.v1.saved_model import load,tag_constants


C:\Users\welcome\anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:526: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
C:\Users\welcome\anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:527: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
C:\Users\welcome\anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:528: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
C:\Users\welcome\anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:529: FutureWarnin

In [2]:
import os
import numpy as np
import tensorflow as tf
from time import strftime 
from PIL  import Image

In [3]:
x_train_path='MNIST/digit_xtrain.csv'
x_test_path='MNIST/digit_xtest.csv'
y_train_path='MNIST/digit_ytrain.csv'
y_test_path='MNIST/digit_ytest.csv'
logging_path='tensorboard_cifar_logs1/'
nr_classes=10
validation_size=10000
image_width=28
image_height=28
channels=1
total_inputs=image_height*image_width*channels

In [4]:
%%time
y_train_all=np.loadtxt(y_train_path,delimiter=',',dtype=int)
y_test=np.loadtxt(y_test_path,delimiter=',',dtype=int)

Wall time: 256 ms


In [5]:
y_train_all.shape
y_train_all

array([5, 0, 4, ..., 5, 6, 8])

In [1]:
x_train_all=np.loadtxt(x_train_path,delimiter=',',dtype=int)
x_train_all[0]


NameError: name 'np' is not defined

In [7]:
x_test=np.loadtxt(x_test_path,delimiter=',',dtype=int)
x_train_all.shape
x_test.shape

(10000, 784)

In [8]:
x_train_all.shape

(60000, 784)

In [9]:
np.savetxt('x_test0_ylabel7.txt',X=[x_test[0]],delimiter=", ",fmt='%1.2f')

In [175]:
values=y_train_all[:5]

In [176]:
x_train_all,x_test=x_train_all/225.0,x_test/255.0

In [177]:
print(values)
np.eye(10)[values]

[5 0 4 1 9]


array([[0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [178]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

# convert target values to one hot encoding

In [179]:
y_train_all=np.eye(10)[y_train_all]

In [180]:
y_train_all.shape


(60000, 10)

In [580]:
y_test=np.eye(10)[y_test]


IndexError: arrays used as indices must be of integer (or boolean) type

In [ ]:
y_test.shape

# create validation data set

In [793]:
x_val=x_train_all[:validation_size]
y_val=y_train_all[:validation_size]
x_train=x_train_all[validation_size:]
y_train=y_train_all[validation_size:]


# setup tesorflow graph

In [794]:
x=tf.placeholder(tf.float32,shape=[None,total_inputs],name='X')

y=tf.placeholder(tf.float32,shape=[None,10],name='labels')



#  neural network architecture
# hyperparameters 

In [795]:
nr_epochs=20
learning_rate=1e-3

n_hidden1=512
n_hidden2=64




In [796]:
def setup_layer(input,weight_dim,bias_dim,name):
    with tf.name_scope(name):
        initial_w=tf.truncated_normal(shape=weight_dim,stddev=0.1,seed=42)
        w=tf.Variable(initial_value=initial_w,name='w')
        initial_b=tf.constant(value=0,shape=bias_dim,dtype=tf.float32)
        b=tf.Variable(initial_value=initial_b,name='b')
        layer_in=tf.matmul(input,w)+b
        if(name=='out'):
            layer_out=tf.nn.softmax(layer_in)
        else:
            layer_out=tf.nn.relu(layer_in)
        tf.summary.histogram('weights',w)
        tf.summary.histogram('biases',b)
        return layer_out
        

In [797]:

#layer_1=setup_layer(x,weight_dim=[total_inputs,n_hidden1],bias_dim=[n_hidden1],name="layer_1")
# layer_2=setup_layer(layer_1,weight_dim=[n_hidden1,n_hidden2],bias_dim=[n_hidden2],name="layer_2")
# output=setup_layer(layer_2,weight_dim=[n_hidden2,nr_classes],bias_dim=[nr_classes],name="out")
# model_name=f'{n_hidden1}-{n_hidden2} LR{learning_rate} E{nr_epochs}'

In [798]:
layer_1=setup_layer(x,weight_dim=[total_inputs,n_hidden1],bias_dim=[n_hidden1],name="layer_1")
layer_drop=tf.nn.dropout(layer_1,keep_prob=0.8,name='dropout_layer')
layer_2=setup_layer(layer_drop,weight_dim=[n_hidden1,n_hidden2],bias_dim=[n_hidden2],name="layer_2")
output=setup_layer(layer_2,weight_dim=[n_hidden2,nr_classes],bias_dim=[nr_classes],name="out")
model_name=f'{n_hidden1}-dropout-{n_hidden2} LR{learning_rate} E{nr_epochs}'

# tensorboard setup

In [799]:
folder_name=f'{model_name} at {strftime("%H  %M")}'
directory=os.path.join(logging_path,folder_name)
try:
    os.makedirs(directory)
except OSError as exception:
    print(exception.strerror)
else:
    print('sucessfuly created')

sucessfuly created


# loss optimiser and metrics

In [800]:
with tf.name_scope('loss_calc'):
    loss=tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits_v2(labels=y,logits=output))

In [801]:
with tf.name_scope('optimiser'):
    optimiser=tf.train.AdamOptimizer(learning_rate=learning_rate)
    train_step=optimiser.minimize(loss)

# accuracy matric

In [802]:
with tf.name_scope('accuracy_caalc'):
    model_prediction=tf.argmax(output,axis=1,name='prediction')
    correct_pred=tf.equal(model_prediction,tf.argmax(y,axis=1))
    accuracy=tf.reduce_mean(tf.cast(correct_pred,tf.float32))

In [803]:
with tf.name_scope('perpormance'):
    tf.summary.scalar('accuracy',accuracy)
    tf.summary.scalar('cost',loss)

# check inout images in tensorboard 

In [804]:
with tf.name_scope('show_image'):
    x_image=tf.reshape(x,[-1,28,28,1])
    tf.summary.image('image input',x_image,max_outputs=4)

INFO:tensorflow:Summary name image input is illegal; using image_input instead.


## setup filewriter merge summaries

In [805]:
merged_summary=tf.summary.merge_all()

In [806]:
train_writer=tf.summary.FileWriter(directory+'/train')
train_writer.add_graph(sess.graph)
validation_writer=tf.summary.FileWriter(directory+'/validation')

In [807]:
sess=tf.Session()

In [808]:
# initailse all variables
init=tf.global_variables_initializer()
sess.run(init)

In [809]:
#w1.eval(sess)

In [810]:
#b3.eval(sess)

# batching data

In [811]:
print(y_train.shape[0])
size_of_batch=1000
num_examples=y_train.shape[0]

50000


In [812]:
nr_iterations=int(num_examples/size_of_batch)
index_in_epoch=0

In [813]:
def next_batch(batch_size,data,labels):
    global num_examples
    global index_in_epoch
    start=index_in_epoch
    
    index_in_epoch=index_in_epoch+batch_size
    if(index_in_epoch>num_examples):
        start=0
        index_in_epoch=batch_size
    end=index_in_epoch
   
    return data[start:end],labels[start:end]

In [814]:
for epoch in range(nr_epochs):
    #-------training data
    for i in range(nr_iterations):
        batch_x,batch_y=next_batch(batch_size=size_of_batch,data=x_train,labels=y_train)
        feed_dictionary={x:batch_x,y:batch_y}
        sess.run(train_step,feed_dict=feed_dictionary)
    s,batch_accuracy=sess.run(fetches=[merged_summary,accuracy],feed_dict=feed_dictionary)
    train_writer.add_summary(s,epoch)
    print(f'epoch {epoch}  training acccuracy={batch_accuracy}')
    #-----validation data set=========
    
    
    summary=sess.run(fetches=merged_summary,feed_dict={x:x_val,y:y_val})
    validation_writer.add_summary(summary,epoch)
print('done training')

epoch 0  training acccuracy=0.8450000286102295
epoch 1  training acccuracy=0.8569999933242798
epoch 2  training acccuracy=0.8650000095367432
epoch 3  training acccuracy=0.875
epoch 4  training acccuracy=0.8740000128746033
epoch 5  training acccuracy=0.9359999895095825
epoch 6  training acccuracy=0.9779999852180481
epoch 7  training acccuracy=0.9800000190734863
epoch 8  training acccuracy=0.9819999933242798
epoch 9  training acccuracy=0.9829999804496765
epoch 10  training acccuracy=0.9819999933242798
epoch 11  training acccuracy=0.984000027179718
epoch 12  training acccuracy=0.9890000224113464
epoch 13  training acccuracy=0.9869999885559082
epoch 14  training acccuracy=0.9900000095367432
epoch 15  training acccuracy=0.9890000224113464
epoch 16  training acccuracy=0.9900000095367432
epoch 17  training acccuracy=0.9869999885559082
epoch 18  training acccuracy=0.9890000224113464
epoch 19  training acccuracy=0.9900000095367432
done training


# saving a model

In [815]:
outputs={'accuracy_caalc/prediction':model_prediction}
inputs={'X':x}
tf.compat.v1.saved_model.simple_save(sess,'savedmodel',inputs,outputs)

Instructions for updating:
This function will only be available through the v1 compatibility library as tf.compat.v1.saved_model.simple_save.
Instructions for updating:
This function will only be available through the v1 compatibility library as tf.compat.v1.saved_model.utils.build_tensor_info or tf.compat.v1.saved_model.build_tensor_info.
INFO:tensorflow:Assets added to graph.
INFO:tensorflow:No assets to write.
INFO:tensorflow:SavedModel written to: savedmodel\saved_model.pb


# make prediction

In [816]:
img=Image.open('MNIST/test_img.png')
img

In [817]:
bw=img.convert('L')
bw

In [818]:

img_array=np.invert(bw)
img_array.shape

(28, 28)

In [819]:
test_img=img_array.ravel()
test_img.shape

(784,)

In [820]:
prediction=sess.run(fetches=tf.argmax(output,axis=1),feed_dict={x:[test_img]})

In [821]:
print(f'prediction for test image{prediction}')

prediction for test image[2]


# testing and evaluation

In [822]:
test_accuracy=sess.run(fetches=accuracy,feed_dict={x:x_test,y:y_test})
print(f' accuracy  on test set {test_accuracy: 0.2%}')

 accuracy  on test set  97.31%


In [835]:
graph=tf.Graph()
sess=tf.Session(graph=graph)


In [839]:
load(sess=sess,tags=[tag_constants.SERVING],export_dir='savedmodel')

INFO:tensorflow:Restoring parameters from savedmodel\variables\variables


meta_info_def {
  stripped_op_list {
    op {
      name: "Add"
      input_arg {
        name: "x"
        type_attr: "T"
      }
      input_arg {
        name: "y"
        type_attr: "T"
      }
      output_arg {
        name: "z"
        type_attr: "T"
      }
      attr {
        name: "T"
        type: "type"
        allowed_values {
          list {
            type: DT_BFLOAT16
            type: DT_HALF
            type: DT_FLOAT
            type: DT_DOUBLE
            type: DT_UINT8
            type: DT_INT8
            type: DT_INT16
            type: DT_INT32
            type: DT_INT64
            type: DT_COMPLEX64
            type: DT_COMPLEX128
            type: DT_STRING
          }
        }
      }
    }
    op {
      name: "ApplyAdam"
      input_arg {
        name: "var"
        type_attr: "T"
        is_ref: true
      }
      input_arg {
        name: "m"
        type_attr: "T"
        is_ref: true
      }
      input_arg {
        name: "v"
        type_attr: "T

In [841]:
x=graph.get_tensor_by_name('X:0')
y_pred=graph.get_tensor_by_name('accuracy_caalc/prediction:0')
prediction=sess.run(fetches=y_pred,feed_dict={x:x_test})


In [842]:
y_test[:5]

array([[0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.]])

In [843]:
prediction[:5]

array([7, 2, 1, 0, 4], dtype=int64)

In [851]:
# % correctly predicted
nr_correct=sum(np.equal(prediction,np.argmax(y_test,axis=1)))
print(nr_correct/len(prediction))
sess.close()
tf.reset_default_graph()

0.9739


In [823]:
train_writer.close()
validation_writer.close()
sess.close()
tf.reset_default_graph()

In [824]:
# with tf.name_scope('hidden_1'):
#     initial_w1=tf.truncated_normal(shape=[total_inputs,n_hidden1],stddev=0.1,seed=42)
#     w1=tf.Variable(initial_value=initial_w1,name='w1')
#     initial_b1=tf.constant(value=0,shape=[n_hidden1],dtype=tf.float32)
#     b1=tf.Variable(initial_value=initial_b1,name='b1')
#     layer_in=tf.matmul(x,w1)+b1
#     layer1_out=tf.nn.relu(layer_in)

In [825]:
# with tf.name_scope('hidden_2'):
#     initial_w2=tf.truncated_normal(shape=[n_hidden1,n_hidden2],stddev=0.1,seed=42)
#     w2=tf.Variable(initial_value=initial_w2,name='w2')

#     initial_b2=tf.constant(value=0,shape=[n_hidden2],dtype=tf.float32)
#     b2=tf.Variable(initial_value=initial_b2,name='b2')
#     layer2_in=tf.matmul(layer1_out,w2)+b2
#     layer2_out=tf.nn.relu(layer2_in)


In [826]:
# 
